import { useEffect, useRef, useState } from 'react'
import './App.css'
import { createStadiumAudio } from './audio'

const W = 800, H = 600, FIELD = { x: 0, y: 0, w: 1200, h: 720 }, GOAL = { depth: 34, halfWidth: 82 }
const HISTORY_KEY = 'pixel-strikers-history'
const formations = { '4-1-0': [[100,285],[210,140],[210,250],[210,390],[330,285]], '3-2': [[100,285],[220,165],[220,285],[220,405],[340,285]] }
const countries = [
  { name:'Japan', flag:'JP', colors:['#ef5350','#fff'], skins:['#f0c6a0','#d69b78','#a96d52'], hair:['#20252b','#48362d'] },
  { name:'Brazil', flag:'BR', colors:['#f4d35e','#249c58'], skins:['#8d553c','#b87655','#5b392e'], hair:['#1e1714','#34221c'] },
  { name:'France', flag:'FR', colors:['#315bb5','#f0d9c0'], skins:['#f0c6a0','#c68b68','#85513d'], hair:['#4a3329','#20252b'] },
  { name:'Nigeria', flag:'NG', colors:['#35bd72','#fff'], skins:['#5d392e','#8e563d','#b97856'], hair:['#191616','#32211c'] },
  { name:'Mexico', flag:'MX', colors:['#e85d5d','#f2efe0'], skins:['#b87554','#d89d78','#7d4d3d'], hair:['#2d211d','#111519'] },
  { name:'Spain', flag:'ES', colors:['#e6483d','#f4cf55'], skins:['#f0c6a0','#d79b75','#a5684d'], hair:['#3a261e','#1c2022'] },
  { name:'USA', flag:'US', colors:['#477bd4','#ed6670'], skins:['#efc9ac','#b97958','#875039'], hair:['#8b5b39','#24282b'] },
  { name:'Korea', flag:'KR', colors:['#eef1f6','#df5360'], skins:['#f0c6a0','#d29a76','#a66c54'], hair:['#171b22','#4d3429'] },
  { name:'Ghana', flag:'GH', colors:['#d54842','#f2cf4a'], skins:['#5b362a','#89523a','#b27152'], hair:['#171515','#33211c'] },
  { name:'Italy', flag:'IT', colors:['#4b9bdb','#f2eee0'], skins:['#f2cdb0','#dca37c','#9c634b'], hair:['#35261f','#1b1c21'] },
]
const roles = ['GK','DF','DF','DF','MF']
const clamp = (n,a,b) => Math.max(a, Math.min(b,n))
const dist = (a,b) => Math.hypot(a.x-b.x,a.y-b.y)
const readHistory = () => { try { return JSON.parse(localStorage.getItem(HISTORY_KEY)) || [] } catch { return [] } }

function makePlayers(team, formation, country) {
  const data = countries[country]
  const keeperKit = [['#f4c542','#4a234c'],['#3de0c2','#123b66'],['#ff8b3d','#3b1d58'],['#f2f25e','#126b55'],['#ee74bd','#342064']][country % 5]
  return formations[formation].map(([x,y], i) => ({ id:`${team}-${i}`, team, x:team==='red'?x*1.12:FIELD.w-x*1.12, y:y*1.38-32, baseX:team==='red'?x*1.12:FIELD.w-x*1.12, baseY:y*1.38-32, vx:0, vy:0, faceX:team==='red'?1:-1, faceY:0, stamina:100, role:roles[i], rating:{shooting:62+i*5, speed:68+(4-i)*4, stamina:74+i*4, tackling:65+(i%3)*8}, skin:data.skins[i%data.skins.length], hair:data.hair[i%data.hair.length], country:data.name, colors:i===0?keeperKit:data.colors, keeperKit, tackle:0 }))
}
function initialState(formation, playerCountry, aiCountry) { return { players:[...makePlayers('red',formation,playerCountry),...makePlayers('blue',formation,aiCountry)], ball:{x:FIELD.w/2,y:FIELD.h/2,vx:0,vy:0,team:null,noCapture:0}, owner:null, score:[0,0], time:180, selected:4, possession:50, possessionTime:[0,0], event:'', paused:false, ended:false, substitution:false, fanPhase:0, camera:{x:FIELD.w/2,y:FIELD.h/2}, actionCooldown:0, aiCooldown:0, charge:0, aiPlan:0, aiPlanTimer:0 } }

export default function App() {
  const canvasRef=useRef(null), gameRef=useRef(null), keys=useRef({}), keyPressAt=useRef({}), audio=useRef(null)
  const [screen,setScreen]=useState('menu'), [difficulty,setDifficulty]=useState('Normal'), [formation,setFormation]=useState('4-1-0'), [playerCountry,setPlayerCountry]=useState(0), [aiCountry,setAiCountry]=useState(1), [audioOn,setAudioOn]=useState(true)
  const [history,setHistory]=useState(readHistory), [hud,setHud]=useState({score:[0,0],time:180,stamina:100,possession:50,selected:'MF',rating:null}), [tab,setTab]=useState(false)
  const startMatch=()=>{ if(playerCountry===aiCountry)return; keys.current={}; keyPressAt.current={}; audio.current?.close(); audio.current=createStadiumAudio(); audio.current?.startAmbient(); gameRef.current=initialState(formation,playerCountry,aiCountry); setScreen('match') }
  const finishMatch=()=>{ const g=gameRef.current; audio.current?.stopAmbient(); const item={score:g.score,difficulty,date:new Date().toLocaleDateString(),result:g.score[0]>=g.score[1]?'W':'L',teams:`${countries[playerCountry].name} v ${countries[aiCountry].name}`}; const next=[item,...history].slice(0,10);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));setHistory(next);setScreen('post') }
  const sound=(method,...args)=>{ if(audioOn) audio.current?.[method]?.(...args) }
  useEffect(()=>{ const down=e=>{const key=e.code==='Space'?' ':e.key.toLowerCase(),fresh=!keys.current[key];keys.current[key]=true;if(fresh)keyPressAt.current[key]=performance.now();if([' ','enter','arrowup','arrowdown','arrowleft','arrowright','tab'].includes(key))e.preventDefault();if(fresh&&key==='t')keys.current.tackleRequested=true;if(fresh&&key==='p'&&gameRef.current){gameRef.current.paused=!gameRef.current.paused;setHud(h=>({...h}))}if(fresh&&key==='q'&&gameRef.current)gameRef.current.selected=(gameRef.current.selected+1)%5;if(fresh&&key==='tab')setTab(v=>!v)};const up=e=>{const key=e.code==='Space'?' ':e.key.toLowerCase();if(key===' '||key==='enter'){keys.current.kickPower=clamp((performance.now()-(keyPressAt.current[key]||performance.now()))/750,.15,1);keys.current.kickRequested=true}keys.current[key]=false};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[])
  useEffect(()=>{if(screen!=='match')return;let frame,last=performance.now();const loop=now=>{const dt=Math.min((now-last)/1000,.04);last=now;const g=gameRef.current,k=keys.current;if(g&&!g.paused&&!g.ended){updateGame(g,k,dt,difficulty,sound,finishMatch);const p=g.players[g.selected];setHud({score:g.score,time:g.time,stamina:p.stamina,possession:g.possession,selected:p.role,rating:p.rating})}draw(canvasRef.current,g);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[screen,difficulty,audioOn])
  const totalWins=history.filter(x=>x.result==='W').length,totalLoss=history.length-totalWins, currentTeam=countries[playerCountry], opponentTeam=countries[aiCountry]
  return <div className="app"><div className="shell"><header className="topbar"><div><div className="kicker">SNES LEAGUE // EXHIBITION 01</div><div className="brand">PIXEL STRIKERS</div></div><div className="record">RECORD <strong>{totalWins} - {totalLoss}</strong></div></header>
    <main className="game-frame"><canvas ref={canvasRef} width={W} height={H}/>{screen==='match'&&<><div className="hud"><div className="team red">{currentTeam.flag} {currentTeam.name.toUpperCase()}</div><div className="score">{gameRef.current?.paused&&<span className="pause-mark">Ⅱ</span>}{hud.score[0]} — {hud.score[1]}<span className="clock">{Math.floor(hud.time/60)}:{String(Math.floor(hud.time%60)).padStart(2,'0')}</span></div><div className="team blue">{opponentTeam.name.toUpperCase()} {opponentTeam.flag}</div></div><div className="bottom-hud"><div className="stamina">{hud.selected} STAMINA<div className="bar"><i style={{width:`${hud.stamina}%`}}/></div><small>SPD {hud.rating?.speed} · TACKLE {hud.rating?.tackling} · KICK {hud.rating?.shooting}</small></div><div className="hint"><b>WASD</b> MOVE &nbsp; <b>SPACE</b> KICK (HOLD) &nbsp; <b>T</b> TACKLE &nbsp; <b>SHIFT</b> SPRINT &nbsp; <b>Q</b> SWITCH &nbsp; <b>P</b> PAUSE</div></div>{gameRef.current?.paused&&<div className="overlay"><div className="modal"><div className="kicker">MATCH CONTROL</div><h2>Ⅱ &nbsp; MATCH PAUSED</h2><p>The whistle is down. Your players are holding their shape.</p><div className="modal-row"><button className="primary" onClick={()=>{gameRef.current.paused=false;setHud(h=>({...h}))}}>RESUME</button><button className="ghost" onClick={()=>setScreen('menu')}>QUIT MATCH</button></div></div></div>}{tab&&<div className="overlay"><div className="modal"><h2>TACTICAL BOARD</h2><div className="stats"><div className="stat">FORMATION<strong>{formation}</strong></div><div className="stat">POSSESSION<strong>{hud.possession}%</strong></div><div className="stat">MATCH<strong>3 MIN</strong></div></div><h2 className="mini-title">{hud.selected} RATINGS</h2><div className="rating-grid">{hud.rating&&Object.entries(hud.rating).map(([key,value])=><span key={key}>{key}<b>{value}</b></span>)}</div><button className="primary" onClick={()=>setTab(false)}>BACK TO MATCH</button></div></div>}</>}
      {screen==='menu'&&<div className="overlay menu-overlay"><div className="modal menu-modal"><div className="kicker">5V5 TOP-DOWN FOOTBALL // MANAGER DESK</div><h1>BUILD YOUR<br/>LINEUP.</h1><p>Pick a country, shape the five, then play through the noise.</p><div className="select-grid"><div><label>YOUR COUNTRY</label><select value={playerCountry} onChange={e=>setPlayerCountry(+e.target.value)}>{countries.map((c,i)=><option value={i} key={c.name}>{c.flag} {c.name}</option>)}</select></div><div><label>OPPONENT</label><select value={aiCountry} onChange={e=>setAiCountry(+e.target.value)}>{countries.map((c,i)=><option value={i} key={c.name}>{c.flag} {c.name}</option>)}</select></div></div><h2>AI DIFFICULTY</h2><div className="options">{['Easy','Normal','Hard'].map(x=><button className={`option ${difficulty===x?'selected':''}`} onClick={()=>setDifficulty(x)} key={x}>{x}<small>{x==='Easy'?'space & time':x==='Normal'?'match day':'pressing machine'}</small></button>)}</div><h2>FORMATION</h2><div className="options two">{Object.keys(formations).map(x=><button className={`option ${formation===x?'selected':''}`} onClick={()=>setFormation(x)} key={x}>{x}<small>{x==='4-1-0'?'balanced':'aggressive'}</small></button>)}</div><div className="modal-row"><button className={`ghost audio-button ${audioOn?'active':''}`} onClick={()=>setAudioOn(v=>!v)}>{audioOn?'AUDIO ON':'AUDIO OFF'}</button><button className="primary" onClick={startMatch}>KICK OFF <span>→</span></button></div></div></div>}
      {screen==='post'&&<div className="overlay"><div className="modal"><div className="kicker">FULL TIME // {currentTeam.name} v {opponentTeam.name}</div><h1>{history[0]?.result==='W'?'NICE ONE.':'NEXT MATCH.'}</h1><div className="score" style={{margin:'18px 0 24px'}}>{history[0]?.score[0]} — {history[0]?.score[1]}</div><div className="stats"><div className="stat">WINS<strong>{totalWins}</strong></div><div className="stat">LOSSES<strong>{totalLoss}</strong></div><div className="stat">GAMES<strong>{history.length}</strong></div></div><button className="primary" onClick={()=>setScreen('menu')}>PLAY AGAIN</button></div></div>}</main>
    <section className="panel"><div className="kicker">MATCH ARCHIVE</div><h2>LAST RESULTS</h2><div className="history">{history.length?history.map((x,i)=><div className="history-row" key={i}><span className={x.result==='W'?'win':'loss'}>{x.result==='W'?'WIN':'LOSS'} // {x.score[0]} - {x.score[1]}</span><span>{x.teams} · {x.difficulty} · {x.date}</span></div>):<div className="history-row"><span>No matches logged yet.</span><span>Play your first fixture</span></div>}</div></section></div></div>
}

const byId=(g,id)=>g.players.find(p=>p.id===id), owner=g=>g.owner?byId(g,g.owner):null
const moveTo=(p,t,s,dt)=>{if(p.stunned>0){p.vx=p.vy=0;return}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);if(d>1){p.faceX=dx/d;p.faceY=dy/d;p.vx=p.faceX*s;p.vy=p.faceY*s;const gk=p.role==='GK',minX=gk?(p.team==='red'?18:FIELD.w-155):8,maxX=gk?(p.team==='red'?155:FIELD.w-18):FIELD.w-8;p.x=clamp(p.x+p.vx*dt,minX,maxX);p.y=clamp(p.y+p.vy*dt,gk?FIELD.h/2-150:8,gk?FIELD.h/2+150:FIELD.h-8)}else p.vx=p.vy=0}
const takeBall=(g,p)=>{const previous=owner(g),red=g.players.filter(x=>x.team==='red');g.owner=p.id;g.ball.team=p.team;g.ball.vx=g.ball.vy=0;g.ball.saved=false;g.ball.noCapture=0;if(p.team==='red')g.selected=g.players.indexOf(p);else if(previous?.team==='red'){const next=red.filter(x=>!x.stunned||x.stunned<=0).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(next)g.selected=g.players.indexOf(next)}}
function releaseBall(g,p,t,power){const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy)||1;g.owner=null;g.ball.team=p.team;g.ball.saveChecked=false;g.ball.noCapture=.14;g.ball.x=p.x+dx/d*22;g.ball.y=p.y+dy/d*22;g.ball.vx=dx/d*power;g.ball.vy=dy/d*power}
function tackle(g,p,sound){if(p.stunned)return false;const o=owner(g);if(!o||o.team===p.team||dist(p,o)>46)return false;const dx=o.x-p.x,dy=o.y-p.y,d=Math.hypot(dx,dy)||1,straight=(p.faceX*dx+p.faceY*dy)/d;if(straight<.18)return false;p.tackle=.24;const chance=clamp(.18+(p.rating.tackling-o.rating.speed)*.009+(straight+.2)*.20,.14,.62)*(p.team==='blue'?.76:1);if(straight>=.68||Math.random()<chance){o.stunned=1.35;setTimeout(()=>o.stunned=0,1350);takeBall(g,p);sound('kick');return true}return false}
function support(g,p){const sign=p.team==='red'?1:-1,o=owner(g),attack=o?.team===p.team,shift=clamp((g.ball.x-FIELD.w/2)*.22,-110,110),runner=p.role==='MF'||p.id.endsWith('-3');let x=p.baseX+shift,y=p.baseY+clamp((g.ball.y-FIELD.h/2)*.18,-55,55);if(attack&&p.role==='MF')x+=sign*155;if(attack&&runner&&p.role!=='MF')x+=sign*130;if(attack&&p.role==='DF'&&!runner)x+=sign*42;if(!attack&&p.role==='DF')x-=sign*45;return{x:clamp(x,35,FIELD.w-35),y:clamp(y,35,FIELD.h-35)}}
function tryKeeperSave(g){const ball=g.ball;if(ball.saveChecked||g.owner||Math.abs(ball.y-FIELD.h/2)>GOAL.halfWidth+28)return;const defending=ball.vx<0?'red':ball.vx>0?'blue':null;if(!defending)return;const keeper=g.players.find(p=>p.team===defending&&p.role==='GK');const approaching=defending==='red'?ball.x<120:ball.x>FIELD.w-120;if(!approaching)return;ball.saveChecked=true;const speed=Math.hypot(ball.vx,ball.vy),corner=Math.abs(ball.y-FIELD.h/2)/GOAL.halfWidth,chance=clamp(.65-speed/1500-corner*.22,.12,.72);if(Math.random()<chance){takeBall(g,keeper);const direction=keeper.team==='red'?1:-1;releaseBall(g,keeper,{x:keeper.x+direction*(FIELD.w*.7),y:FIELD.h/2+(Math.random()-.5)*260},shotPower(keeper,1));ball.saved=false}}
function restartAfterGoal(g,scored){g.players.forEach(p=>{p.x=p.baseX;p.y=p.baseY;p.vx=p.vy=0;p.stunned=0});const team=scored==='red'?'blue':'red',kicker=g.players.find(p=>p.team===team&&p.role==='MF');kicker.x=FIELD.w/2+(team==='red'?-20:20);kicker.y=FIELD.h/2;kicker.faceX=team==='red'?1:-1;kicker.faceY=0;g.ball.x=FIELD.w/2;g.ball.y=FIELD.h/2;g.ball.vx=g.ball.vy=0;g.owner=null;takeBall(g,kicker);if(team==='blue'){const next=g.players.filter(p=>p.team==='red').sort((a,b)=>dist(a,kicker)-dist(b,kicker))[0];g.selected=g.players.indexOf(next)}}
const shotPower=(p,charge=1)=>90+charge*(520+p.rating.shooting*2)
function updateGame(g,k,dt,difficulty,sound,finish){
  g.time-=dt;if(g.time<=0){g.time=0;finish();return}g.actionCooldown=Math.max(0,g.actionCooldown-dt);g.aiCooldown=Math.max(0,g.aiCooldown-dt);g.aiPlanTimer-=dt;if(g.aiPlanTimer<=0){g.aiPlan=(g.aiPlan+1+Math.floor(Math.random()*2))%3;g.aiPlanTimer=difficulty==='Hard'?3.2:4.8}
  g.players.forEach(p=>{p.tackle=Math.max(0,p.tackle-dt);p.stamina=clamp(p.stamina+(p.vx||p.vy?-5:p.rating.stamina*.1)*dt,0,100)})
  const ball=g.ball,looseDefenders=g.players.filter(p=>p.team==='red'&&!p.stunned&&p.x<=ball.x+35),fallback=g.players.filter(p=>p.team==='red'&&!p.stunned),next=(looseDefenders.length?looseDefenders:fallback).sort((a,b)=>dist(a,ball)-dist(b,ball))[0];if(!owner(g)&&next)g.selected=g.players.indexOf(next)
  const human=g.players[g.selected],sprint=k.shift&&human.stamina>1;g.charge=(k[' ']||k.enter)&&!human.stunned?clamp(g.charge+dt/.75,0,1):0;let ax=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),ay=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0),m=Math.hypot(ax,ay)
  if(m){human.faceX=ax/m;human.faceY=ay/m;moveTo(human,{x:human.x+human.faceX*80,y:human.y+human.faceY*80},(sprint?158:104)+human.rating.speed*.35,dt)}else if(!owner(g)&&human===next)moveTo(human,ball,98,dt);else human.vx=human.vy=0
  if(k.tackleRequested){k.tackleRequested=false;if(g.actionCooldown<=0){tackle(g,human,sound);g.actionCooldown=.42}}
    if(k.kickRequested){const power=Math.max(g.charge,k.kickPower||.15);k.kickRequested=false;k.kickPower=0;if(!owner(g)&&dist(human,ball)<90)takeBall(g,human);if(owner(g)===human&&!human.stunned&&g.actionCooldown<=0){releaseBall(g,human,{x:human.x+human.faceX*400,y:human.y+human.faceY*400},shotPower(human,power));sound('kick');g.actionCooldown=.34}g.charge=0}
  const chaser=team=>g.players.filter(p=>p.team===team&&!p.stunned).sort((a,b)=>dist(a,ball)-dist(b,ball))[0]
  g.players.filter(p=>p.team==='red'&&p!==human&&owner(g)!==p).forEach(p=>moveTo(p,!owner(g)&&next===p?ball:support(g,p),!owner(g)&&next===p?98:68,dt))
  g.players.filter(p=>p.team==='blue').forEach(p=>{const o=owner(g);if(o===p){if(p.role==='GK'){const direction=-1;releaseBall(g,p,{x:p.x+direction*FIELD.w*.75,y:FIELD.h/2+(Math.random()-.5)*220},shotPower(p,1));sound('kick');g.aiCooldown=.6;return}const lane=FIELD.h/2+(g.aiPlan-1)*125+Math.sin(g.time*1.7+p.y)*28;moveTo(p,{x:clamp(p.x-220,35,FIELD.w-35),y:clamp(lane,55,FIELD.h-55)},92+(difficulty==='Hard'?25:difficulty==='Easy'?-8:8),dt);const shootingRange=difficulty==='Hard'?390:300;if(g.aiCooldown<=0&&p.x<shootingRange){releaseBall(g,p,{x:0,y:clamp(FIELD.h/2+(g.aiPlan-1)*70+Math.sin(g.time)*38,FIELD.h/2-62,FIELD.h/2+62)},shotPower(p,1));sound('kick');g.aiCooldown=difficulty==='Hard'?.58:.82}return}const press=owner(g)?.team==='red'&&chaser('blue')===p;const supportTarget=support(g,p);supportTarget.y=clamp(supportTarget.y+(g.aiPlan-1)*(p.role==='MF'?105:48),35,FIELD.h-35);moveTo(p,press?owner(g):(!owner(g)&&chaser('blue')===p?ball:supportTarget),press?108:72,dt);if(press&&g.aiCooldown<=0&&dist(p,owner(g))<34){tackle(g,p,sound);g.aiCooldown=.55}})
  const o=owner(g);if(o){ball.x=o.x+o.faceX*15;ball.y=o.y+o.faceY*12;ball.vx=o.vx;ball.vy=o.vy;g.possessionTime[o.team==='red'?0:1]+=dt}else{ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.vx*=Math.pow(.16,dt);ball.vy*=Math.pow(.16,dt);ball.noCapture=Math.max(0,ball.noCapture-dt);tryKeeperSave(g);const candidate=ball.noCapture<=0?g.players.filter(p=>!p.stunned&&dist(p,ball)<30).sort((a,b)=>dist(a,ball)-dist(b,ball))[0]:null;if(candidate)takeBall(g,candidate)}
  if(ball.y<0||ball.y>FIELD.h){ball.vy*=-.62;ball.y=clamp(ball.y,0,FIELD.h)}
  if(ball.x<0||ball.x>FIELD.w){if(Math.abs(ball.y-FIELD.h/2)<GOAL.halfWidth){const scored=ball.x<0?'blue':'red';g.score[scored==='red'?0:1]++;g.event=scored==='red'?'GOAL!':'THEY SCORE';sound('goal',scored==='red');restartAfterGoal(g,scored);setTimeout(()=>g.event='',900)}else{ball.vx*=-.65;ball.x=clamp(ball.x,0,FIELD.w)}}
  const total=g.possessionTime[0]+g.possessionTime[1];g.possession=total?Math.round(g.possessionTime[0]/total*100):50;const focus=owner(g)||human;g.camera.x+=(clamp((focus.x+ball.x)/2,170,FIELD.w-170)-g.camera.x)*Math.min(1,dt*3);g.camera.y+=(clamp((focus.y+ball.y)/2,145,FIELD.h-145)-g.camera.y)*Math.min(1,dt*3)
}

function project(g,x,y){const z=.82,dx=x-g.camera.x,dy=y-g.camera.y;return{x:W/2+(dx+dy*.24)*z,y:H/2+(dy*.60-dx*.10)*z,scale:z}}
function pitchLine(c,g,a,b){const p=project(g,a.x,a.y),q=project(g,b.x,b.y);c.moveTo(p.x,p.y);c.lineTo(q.x,q.y)}
function drawCrowd(c,g){
  const poly=(points,color)=>{c.fillStyle=color;c.beginPath();points.map(p=>project(g,p.x,p.y)).forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fill()}
  c.fillStyle='#122e38';c.fillRect(0,0,W,H)
  poly([{x:-150,y:-145},{x:1350,y:-145},{x:1200,y:-8},{x:0,y:-8}],'#344a55')
  poly([{x:0,y:728},{x:1200,y:728},{x:1350,y:865},{x:-150,y:865}],'#2a3e49')
  const colors=['#e9cf71','#d95a54','#5faad2','#e9e8d6','#934f96']
  for(let row=0;row<4;row++)for(let col=0;col<38;col++){const top=project(g,col*34-35,-118+row*27),bottom=project(g,col*34-35,838-row*27);c.fillStyle=colors[(col+row*3)%colors.length];c.fillRect(top.x,top.y,4,6);c.fillRect(bottom.x,bottom.y,4,6)}
  poly([{x:0,y:0},{x:FIELD.w,y:0},{x:FIELD.w,y:FIELD.h},{x:0,y:FIELD.h}],'#28734c')
  for(let i=0;i<12;i++)poly([{x:i*100,y:0},{x:(i+1)*100,y:0},{x:(i+1)*100,y:FIELD.h},{x:i*100,y:FIELD.h}],i%2?'rgba(7,50,33,.10)':'rgba(255,255,255,.025)')
  c.strokeStyle='#c6e6b7';c.lineWidth=3;c.beginPath();pitchLine(c,g,{x:0,y:0},{x:FIELD.w,y:0});pitchLine(c,g,{x:FIELD.w,y:0},{x:FIELD.w,y:FIELD.h});pitchLine(c,g,{x:FIELD.w,y:FIELD.h},{x:0,y:FIELD.h});pitchLine(c,g,{x:0,y:FIELD.h},{x:0,y:0});pitchLine(c,g,{x:FIELD.w/2,y:0},{x:FIELD.w/2,y:FIELD.h});c.stroke()
  const center=project(g,FIELD.w/2,FIELD.h/2);c.beginPath();c.ellipse(center.x,center.y,59,35,-.1,0,Math.PI*2);c.stroke()
}
function drawGoal(c,g,left){if(left)drawCrowd(c,g);const x=left?0:FIELD.w,back=left?-GOAL.depth:FIELD.w+GOAL.depth,top=FIELD.h/2-GOAL.halfWidth,bottom=FIELD.h/2+GOAL.halfWidth;c.strokeStyle='#edf6e6';c.lineWidth=3;c.beginPath();pitchLine(c,g,{x,y:top},{x:back,y:top});pitchLine(c,g,{x:back,y:top},{x:back,y:bottom});pitchLine(c,g,{x:back,y:bottom},{x,y:bottom});c.stroke();c.strokeStyle='rgba(235,245,229,.5)';c.lineWidth=1;for(let i=1;i<6;i++){const y=top+i*(bottom-top)/6;c.beginPath();pitchLine(c,g,{x,y},{x:back,y});c.stroke()}for(let i=1;i<4;i++){const xx=x+(back-x)*i/4;c.beginPath();pitchLine(c,g,{x:xx,y:top},{x:xx,y:bottom});c.stroke()}}
function draw(canvas,g){
  if(!canvas||!g)return
  const c=canvas.getContext('2d');c.clearRect(0,0,W,H)
  drawCrowd(c,g);drawGoal(c,g,true);drawGoal(c,g,false)
  g.players.slice().sort((a,b)=>a.y-b.y).forEach(p=>{
    const q=project(g,p.x,p.y),s=8
    c.fillStyle='rgba(4,14,12,.38)';c.beginPath();c.ellipse(q.x,q.y+9,14,5,0,0,Math.PI*2);c.fill()
    if(owner(g)===p){c.strokeStyle='#fff4c7';c.lineWidth=2;c.beginPath();c.arc(q.x,q.y,17,0,Math.PI*2);c.stroke()}
    if(p.stunned>0){c.save();c.translate(q.x,q.y);c.rotate(-.5);c.fillStyle=p.colors[0];c.fillRect(-15,-5,30,10);c.fillStyle=p.skin;c.beginPath();c.arc(-16,0,6,0,Math.PI*2);c.fill();c.restore()}
    else {c.fillStyle=p.colors[0];c.fillRect(q.x-s,q.y-s,s*2,s*2.1);c.fillStyle=p.skin;c.beginPath();c.arc(q.x,q.y-s-5,6,0,Math.PI*2);c.fill();c.fillStyle=p.hair;c.fillRect(q.x-6,q.y-s-10,12,4)}
    if(p.id===g.players[g.selected].id){c.strokeStyle='#d8f171';c.lineWidth=2;c.strokeRect(q.x-s-4,q.y-s-15,2*s+8,2*s+15);if(g.charge>0){c.fillStyle='#102229';c.fillRect(q.x-16,q.y+18,32,5);c.fillStyle=g.charge>.82?'#ed5b4f':'#d8f171';c.fillRect(q.x-15,q.y+19,30*g.charge,3)}}
  })
  const b=project(g,g.ball.x,g.ball.y);c.fillStyle='rgba(4,14,12,.4)';c.beginPath();c.ellipse(b.x,b.y+5,7,3,0,0,Math.PI*2);c.fill();c.fillStyle='#fff4c7';c.fillRect(b.x-4,b.y-8,8,8)
  if(g.event){c.fillStyle='#fff4c7';c.font='bold 24px Chakra Petch';c.textAlign='center';c.fillText(g.event,W/2,105)}
}
